//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Google Inc.")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright 2015, Google Inc.")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("C# runtime library for Protocol Buffers - Google\'s data interchange format.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("3.12.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.12.3")]
[assembly: System.Reflection.AssemblyProductAttribute("Google.Protobuf")]
[assembly: System.Reflection.AssemblyTitleAttribute("Google Protocol Buffers")]
[assembly: System.Reflection.AssemblyVersionAttribute("3.12.3.0")]

// Von der MSBuild WriteCodeFragment-Klasse generiert.

